name: PR Build Check

on:
  pull_request:
    branches: [master, dev]
    types: [opened, synchronize, reopened]

jobs:
  build-check:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint code
        run: bun lint
        continue-on-error: false

      - name: Check TypeScript compilation
        run: bun tsc --noEmit
        continue-on-error: false

      - name: Build project
        run: bun run build
        continue-on-error: false

      - name: Add PR Comment
        if: always()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ job.status == 'success' && '✅ **Build Check Passed!** The PR is ready for review.' || '❌ **Build Check Failed!** Please fix the issues before requesting a review.' }}
          reactions: ${{ job.status == 'success' && '+1' || '' }}
